### PR TITLE
add methods for moment.js subtract, add, diff

### PR DESCRIPTION
**Pull request by antmurph**
Had trouble with adding .format() to the end of subtract, and add because of render statements being parsed in-between. For this reason these methods expect a format parameter which will be added to the aforementioned moment.js render call.

Issue #35

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Looking through the moment.js docs, both add and subtract take two arguments, not one. How does this work? The diff call can also take two arguments, but appears to also support one in some of the calling options.

**Comment by antmurph** [comment]
I can split up the parameters sent to add or subtract, they have optional parameters though so I decided to sent the entire param as a string in the view. Heres an example with adding 2 days in the format ll

`<strong>Date of Birth with two days added:</strong> {{ moment(employee.dob, local=True).add("2, 'days'", "ll") }}`

**Comment by antmurph** [comment]
What I mean by optional parameters specifically is add/subtract can accept the following

- .add(Number, String)   //ex: (7, 'days')
- .add(Duration)             //ex: (100) // 100 milliseconds
- .add(Object)                //ex: ({days:7,months:1}) //object literal

I found no reason to complicate what's going on and instead of dealing with each param type just pass it directly to moment as a string

**Comment by antmurph** [comment]
for clarity, this is using diff

`<strong>Employee age:</strong> {{ moment(current_date).diff(employee.dob,'years') }}`

**Comment by miguelgrinberg** [comment]
Combining all the JS arguments in a Python string is extremely unintuitive, don't you think? How are people going to guess that is has to be done that way?

**Comment by akibrhast** [comment]
Since the Flask-Moment uses Moment.js to do a lot of the formatting, should the syntax for add and subtract follow similarly?

**Pull request closed without merging**
