### PR TITLE
add an extra parameter for language initialization

### PR DESCRIPTION
**Pull request by SaulOviedo**
Moment js does not change the language once it is rendered. So there should be great if we can pass the language as parameter.

### CODE REVIEW

**Comment by SaulOviedo** [comment]
Thank you for responding! I'm using the last moment js version 2.23 and for some reason once a date is rendered and then moment.locale is updated, those dates does not update to the new language.

I understand that `{{ moment.include_moment() }}  ` will render every date in my page and `{{ moment.lang("es") }}` then will change locale, but they are still in english. Dates render after this statement  `{{ moment.lang("es") }}` do render in spanish. For now, I use a workaround to initialize it in 'es' (spanish).

**Comment by miguelgrinberg** [comment]
@SaulOviedo Hmm. Okay, so here is what I don't understand. The `include_moment` function does not render anything, it just schedules the rendering so that it happens at some point in the future, when the entire page finished loading in the browser.

So the sequence of actions I would have expected is as follows:

- `include_moment()` schedules the rendering when the page finishes loading
- `lang()` call configures the language
- (when page finishes loading) all dates are rendered with the currently set language

If things don't happen as above for you, then we need to find out why.

**Comment by miguelgrinberg** [comment]
And I just tested the example app in this repository with the addition of setting Spanish. Here is the diff:

```
diff --git a/example/templates/index.html b/example/templates/index.html
index 02e9274..94fe49c 100644
--- a/example/templates/index.html
+++ b/example/templates/index.html
@@ -3,6 +3,7 @@
         <title>Flask-Moment example app</title>
         {{ moment.include_jquery() }}
         {{ moment.include_moment() }}
+        {{ moment.lang('es') }}
         <script>
         function load_ajax_timestamp() {
             $.ajax({
```

With this change the page renders all the dates in Spanish. How is your app different than this example?

**Comment by SaulOviedo** [comment]
You are totally right. I did check the example by myself and did work. But for some reason it doesnt work on my personal project. I just folllowed the instructions that are quite easy.

**Comment by SaulOviedo** [comment]
I made some debugging on the javascript adding some console.log at flask_moment.py

This at the beginning, before set locale to english (Default)

    `'''%s<script>
    console.log("english");
    moment.locale("en");
    
    function flask_moment_render(elem) {
        ...
    }`

this at the flask_moment_render_all function, before render:

    function flask_moment_render_all() {
        $('.flask-moment').each(function() {
            console.log(moment.locale());
          flask_moment_render(this);
        if ($(this).data('refresh')) {
           ...
         }

and then at the end of the locale static method, before set locale to spanish:

            return Markup(
                '<script>\nconsole.log("spanish")\nmoment.locale("%s");\n</script>' % language)


After test it. This was the result:
image

We can see that is still set to english before render.

I did run this code on the example file and got the expected result
image

**Comment by miguelgrinberg** [comment]
Is your code available for me to see?

**Comment by SaulOviedo** [comment]
it's available at this repo
https://github.com/SaulOviedo/puntoCarga

All the include stuff is at app\templates\base.html

and the problem is at app\templates\dashboard_company.html, line 50.

you can check the app going at https://sauloviedo95.pythonanywhere.com
user; sauloviedoleon@gmail.com
pass:123456

image

thank you for any help

**Comment by SaulOviedo** [comment]
That was the error 😶 😰 Thank you so much for your help and  your incredible work,Mr @miguelgrinberg. 🎉

**Pull request closed without merging**
