### PR TITLE
add diff support

### PR DESCRIPTION
**Pull request by tryhubov**
hi @miguelgrinberg 

- implemented `diff()`
- https://momentjs.com/docs/#/displaying/difference/
- tried to make minimal changes to simplify review

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
What is the use case in which using `moment.diff` in the template is better than using `timedelta` in Python and then rendering this result directly?

**Comment by tryhubov** [comment]
ok but, why did you add `fromTime` and `toTime` functions? what's the difference between them and `diff` in your lib concept? they are just special cases for `diff`

**Comment by tryhubov** [comment]
nevermind, of course, there is some the difference. maybe it's just matter of taste :) sorry for disturbing you

**Comment by miguelgrinberg** [comment]
I did not want to offend you. I sincerely was asking when would you use diff in the template versus just doing (time1 - time2) in Python.

The `fromTime` and `toTime` (which correspond to `from` and `to` in moment.js) are rendering functions, the do not perform a time calculation. If the distance between the two times was, for example, a day, then you would get something like "in a day" or "a day ago". This cannot be done (easily, at least!) in Python.

**Comment by tryhubov** [comment]
oh, no problem at all, don't worry :)

my main point that it's not so easy to get diff in weeks in python (same as get momentJS-like `from` and `to` output)

also, as i said, probably it's just matter of taste. but it seems not convenient for me to handle this interim "entity" (i mean timedelta) when i have two dates in controller, i need them both in template but also want to show difference between them. for me it's more rendering task. because when i want to make a change in diff representation (e.g. change `days` to `weeks` i intuitively look for a template and don't want to recalculate manually. 



## compare

### approach with timedelta in python

route 
```py
@app.route('/timedelta_py')
def timedelta_py():
    dt1 = datetime.datetime(1971, 1, 1, 0, 0, 0)
    dt2 = datetime.datetime(1970, 1, 1, 0, 0, 0)
    return render_template(
        'timedelta_py.html',
        dt1=dt1,
        dt2=dt2,
        diff_in_days=(dt1 - dt2).days,
    )
```
template
```jinja2
    ...
    dt1: {{ moment(dt1).format('YY/MM/DD') }}
    dt2: {{ moment(dt2).format('YY/MM/DD') }}
    diff: {{ diff_in_days }}
```

### approach using moment js

route 
```py
@app.route('/momentjsdiff')
def momentjsdiff():
    dt1 = datetime.datetime(1971, 1, 1, 0, 0, 0)
    dt2 = datetime.datetime(1970, 1, 1, 0, 0, 0)
    return render_template(
        'momentjsdiff.html',
        dt1=dt1,
        dt2=dt2,
    )
```
template
```jinja2
    ...
    dt1: {{ moment(dt1).format('YY/MM/DD') }}
    dt2: {{ moment(dt2).format('YY/MM/DD') }}
    diff: {{ moment(dt1).diff(dt2, 'days') }}
```

**Pull request merged**
