### PR TITLE
Add basic docs with Sphinx and Flask-Sphinx-Themes

### PR DESCRIPTION
**Pull request by wgwz**
Hey, Miguel. This is a start for adding in docs and addressing #22. I have not worked with Sphinx very much, so any advice you can give me about how to best document this project will be appreciated, and I'll gladly make changes. For example I am not sure how to use these :code:, :class:, or :func: tags and I am also not sure how to use "autodoc". I'm thinking those tags and autodoc probably are work together somehow.

I used the `sphinx-quickstart` and based the remaining configuration off of how [Flask-Misaka](https://flask-misaka.readthedocs.io/en/latest/) did their docs. As you'll see all I've done is copy the readme into _index.rst_. 

I figure at this point I should try to get some feedback before going forward. In meantime, I'll look some more into Sphinx.

Oh, and building the docs should work with:

    pip install sphinx
    pip install Flask-Sphinx-Themes
    make html

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Hi @wgwz! Awesome, thanks for looking at this. The few times I did docs for other projects, it involved a lot of copy pasting. I did not install the sphinx theme separately and instead copied the files over, not sure if a packaged version of this template existed a while back, sounds like a nice improvement.

If you want to see how I've done it, checkout Flask-SocketIO, for example. That one has autodoc enabled, which generates the entire API Reference section from docstrings (see the bottom of [this file](https://raw.githubusercontent.com/miguelgrinberg/Flask-SocketIO/master/docs/index.rst)). If you have any specific questions let me know.

**Comment by wgwz** [comment]
Hey, again. This is probably some that should be obvious but I'm not seeing it at the moment. Why does the `_moment` class create a timestamp when it gets initialized? Or what is it being used for? And, does that time stamp get created when the app gets instantiated? 

This is `\_\_init\_\_ for `_moment`:

    def __init__(self, timestamp=None, local=False):
        """
        Set the initial timestamp.

        :param timestamp: 
        """
        if timestamp is None:
            timestamp = datetime.utcnow()
        self.timestamp = timestamp
        self.local = local

```
class Moment(object):
    def __init__(self, app=None):
        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        if not hasattr(app, 'extensions'):
            app.extensions = {}
        app.extensions['moment'] = _moment
        app.context_processor(self.context_processor)

    @staticmethod
    def context_processor():
        return {
            'moment': current_app.extensions['moment']
        }

    def create(self, timestamp=None):
        return current_app.extensions['moment'](timestamp)
```

**Comment by miguelgrinberg** [comment]
I'm not sure I understand your question, but if you refer specifically to this:

    if timestamp is None:
        timestamp = datetime.utcnow()

the idea is that in the template you can say something like `moment().format('MMMM Do YYYY, h:mm:ss a')` and that would render the current time. So you either pass a timestamp that you have, or don't pass anything and the current time is used.

**Comment by wgwz** [comment]
Yup, that's what I was referring to.  I just wasn't sure when `timestamp` was getting created. I was confused because I was thinking this line: 

    app.extensions['moment'] = _moment

, meant it was getting created when the app gets instantiated. Which it probably is, but it also probably gets created each time the request context gets built. Is this right? I guess that's what this is doing: 

    app.context_processor(self.context_processor)

    @staticmethod
    def context_processor():
        return {
            'moment': current_app.extensions['moment']
        }

**Comment by miguelgrinberg** [comment]
Ah, okay. This assignment:

    app.extensions['moment'] = _moment

is not instantiating anything. It is just storing the class name in a place where it can be found later by the context processor function.

The context processor function also does not instantiate an object, just registers the `_moment` class with the name `moment`, so that it is available in templates.

Only when in the template you say `moment()` an object of that class is created, and the timestamp is created as well.

**Comment by wgwz** [comment]
Thanks for clarifying that. Here's another question for you. Why do we have this:

    @staticmethod
    def locale(language):
        """
        Generates a script tag that sets the users locale and returns it as an
        instance of :class:`jinja2.Markup`.

        :param language: Language used to set the user locale. i.e. "en", "cs", "fr"
        """
        return Markup('<script>\nmoment.locale("%s");\n</script>' % language)

    @staticmethod
    def lang(language):
        """
        Proxy to the :meth:`locale` method.

        :param language: Language used to set the user locale. i.e. "en", "cs", "fr"
        """
        return _moment.locale(language)

I'm sure there's a good reason for it, but to me it just seems like a proxy. If I had to guess, I would say maybe the `lang` method was/is going to be deprecated?

**Comment by miguelgrinberg** [comment]
Old versions of moment.js used `lang()` to configure the language, then at some point they removed that and started using `locale()`. Unlike others, I really hate to break other people's code, so I left `lang()` in there just in case.

**Comment by wgwz** [comment]
What's the reason for "Z" here? 

```
def _timestamp_as_iso_8601(self, timestamp):
        """
        
        """
        tz = ''
        if not self.local:
            tz = 'Z'
        return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
```

**Comment by miguelgrinberg** [comment]
In iso8601 dates, the Z represents UTC time zone.

**Comment by wgwz** [comment]
So server-time, is exactly that, always in UTC. I understand. So `local=False` brings us back to that base ("server-time").

**Comment by miguelgrinberg** [comment]
Right. Most of the time you will be working with UTC time on the server, so that is why `local=False` is the default. Without the Z, the timestamp will assume the time is in the system local time. Since these times will be rendered by JavaScript on the client, setting `local=True` basically means that you have, on the server, a time that is in the local time of the client (not a very common thing).

**Comment by wgwz** [comment]
I'm still a bit confused about this local parameter. `local=True` means to not do the conversion to the clients local time. Does It mean, render the time for the servers local time zone? And of course all the timestamps are stored as UTC "Z" on our server. Still got these docs in the works. And I'm working on tests as well. I might finish the testing first, then finish up this PR.

**Comment by miguelgrinberg** [comment]
No. When `local` is `True`, it means that the time should be used as is, without any timezone adjustments. If you have a time object that is set to 9:30am as stored in the server, then when that time is rendered by moment.js on the client, it will also read 9:30am, regardless of what the TZ is at the client's location.

The idea of calling this `local` is that the time in this case is not UTC, but it is a time that should be treated as local time by each client.

**Comment by wgwz** [comment]
```
def _timestamp_as_iso_8601(self, timestamp):
        tz = ''
        if not self.local:
            tz = 'Z'
        return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
```

> By default the timestamps will be converted from UTC to the local time in each client's machine before rendering. To disable the conversion to local time pass local=True.

So if `local=True` we are going to render the timestamp in UTC. I'm sorry for dragging this out. I just want to make sure I understand what's going on. I'm not sure why I'm having trouble getting this. I'm assuming everything stored on the server is a `datetime.utcnow` object.

I'm pretty sure I get it now. :D

**Comment by miguelgrinberg** [comment]
> So if local=True we are going to render the timestamp in UTC

No, you got it wrong still. If local is `True`, the timestamp is rendered as local time in the machine that is rendering it.

Maybe an example will help. Let's say you have a datetime that is set to today at 8:30pm. This is a [naive](https://docs.python.org/2/library/datetime.html) datetime object, so there is no TZ associated with it. If local=False, a client in Los Angeles that renders this timestamp to a webpage will see 12:30pm. A client in New York will see 3:30pm. And a client in the UK will see 8:30pm. The local=False setting tells Flask-Moment that the timestamps provided by the server should be assumed to be in UTC.

Now if local=True, then Los Angeles, New York, UK and everyone else will see 8:30pm in their local times.

**Comment by wgwz** [comment]
> Now if local=True, then Los Angeles, New York, UK and everyone else will see 8:30pm in their local times.

"in their local times", do you mean everyone sees 8:30pm in their browser?

**Comment by miguelgrinberg** [comment]
Yes

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Please reopen if you need more assistance.

**Pull request closed without merging**
