### PR TITLE
Add auto-detect locale support

### PR DESCRIPTION
**Pull request by greyli**

### CODE REVIEW

**Comment by greyli** [comment]
Any ideas?

**Comment by miguelgrinberg** [comment]
Oh, this looks pretty good! Should have done this long ago, makes a lot more sense.

**Comment by miguelgrinberg** [comment]
I'll test it a little bit and then merge. I'm not sure how this works with the longer locales, such as `en_GB` and so on, I want to verify that before I merge.

**Comment by greyli** [comment]
Thanks. It seems that Moment.js will handle these locales:
> Moment will also try locale specifier substrings from most-specific to least-specific until it finds a locale it knows. This is useful when supplying Moment with a locale string pulled from the user's environment, such as window.navigator.language. - [Docs](https://momentjs.com/docs/#/i18n/changing-locale/)

**Comment by miguelgrinberg** [comment]
Yeah, that seems to work, thanks! I was hoping there was also a way to access the language settings that the browser sends in the `Accept-Language` header, but that does not seem to be accessible from JS. So for the cases where the server uses the Accept header it can very well set the moment local explicitly.

So I'm merging this. Thanks again!

**Comment by greyli** [comment]
It's my pleasure. I notice that the last release was two years ago. Maybe it's time to make a new one?

**Comment by miguelgrinberg** [comment]
@greyli I was going to, but noticed that there is a problem with the Travis builds, so I want to figure that out before I get a new release (since now master releases show as failed).

**Pull request merged**
